### ISSUE TITLE
[MACOS] No Spandoc settings in menu

### ISSUE THREAD

**Issue by kklot** [geniusupgrader/Spandoc#1]
This is a promising package, at least I need it a lot. Now when choose pallet I got your original path
`C:/Users/robin/AppData/Roaming/cabal/bin/pandoc.exe` and cannot find the settings to change this?

**Comment by geniusupgrader** [comment]
After the rewrite, I've forgotten to edit the `Main.sublime-menu`. Now you can go Preferences->Packages Settings->Spandoc and copy the default settings (which now do not contain my path anymore) to your user settings.
Notice however, that I've not tested my package on Mac, only on Linux (and Windows). Altough it should work with Mac.
