### ISSUE TITLE
Linux compatibility?

### ISSUE THREAD

**Issue by j9ac9k** [geniusupgrader/Spandoc#5]
I just installed Spandoc on my linux system, I'm running Sublilme Text Build 3152

Trying to run Spadoc config generates the following in the sublime text console:

```
[Spandoc could not find a default configuration file in Packages/Spandoc/spandoc.sublime-settings]
[Loading from the binary package resource file also failed.]
[e: resource not found]
```
Opening a markdown file and running Spandoc palette generates a pop up with the following content:

```
Error when running:

  c o n v e r t e d _ m a r k d o w n . m d   - f   h t m l   - - t o = l a t e x   - - s t a n d a l o n e   - - t o c   - - n u m b e r - s e c t i o n s   - - w r a p = n o n e   - - p a r s e - r a w   - - l a t e x - e n g i n e = x e l a t e x   - - v a r i a b l e = f o n t s i z e : 1 1 p t   - - v a r i a b l e = p a p e r s i z e : a 4 p a p e r   - o   c o n v e r t e d _ m a r k d o w n . p d f

/bin/sh: converted_markdown.md: command not found
```

the console has the following content:

```
Spandoc: current file path: /home/ogi/converted_markdown.md
Spandoc: Is the settings file "spandoc.json" in the current folder path?
Spandoc: No!
Spandoc: Is the settings file "spandoc.json" somewhere in the project?
Spandoc: (Searching the following folders and their subfolders: [])
Spandoc: Taking either the user_settings_file (if it exists) or the default_settings_file
Spandoc: current file path: /home/ogi/converted_markdown.md
Spandoc: Is the settings file "spandoc.json" in the current folder path?
Spandoc: No!
Spandoc: Is the settings file "spandoc.json" somewhere in the project?
Spandoc: (Searching the following folders and their subfolders: [])
Spandoc: Taking either the user_settings_file (if it exists) or the default_settings_file
Spandoc: output_extension: pdf
Spandoc: output_name_with_ext: converted_markdown.pdf
Spandoc: pandoc_cmd:  converted_markdown.md -f html --to=latex --standalone --toc --number-sections --wrap=none --parse-raw --latex-engine=xelatex --variable=fontsize:11pt --variable=papersize:a4paper -o converted_markdown.pdf
error: Error when running:

  c o n v e r t e d _ m a r k d o w n . m d   - f   h t m l   - - t o = l a t e x   - - s t a n d a l o n e   - - t o c   - - n u m b e r - s e c t i o n s   - - w r a p = n o n e   - - p a r s e - r a w   - - l a t e x - e n g i n e = x e l a t e x   - - v a r i a b l e = f o n t s i z e : 1 1 p t   - - v a r i a b l e = p a p e r s i z e : a 4 p a p e r   - o   c o n v e r t e d _ m a r k d o w n . p d f

/bin/sh: converted_markdown.md: command not found
```

Suggestions?

**Comment by geniusupgrader** [comment]
Try to set the pandoc_path variable to your pandoc executable, like this:
`"pandoc_path": "/usr/local/bin/pandoc",`

If this is not working, write me again

**Comment by geniusupgrader** [comment]
It was just a problem with lowercase/uppercase on Linux. I thought I had fixed it with #3. But I have overseen something..

**Comment by j9ac9k** [comment]
Still having an issue, but progress is made!


from my `Packages/Spandoc/package-metadata.json`

```json
{"version": "3.0.6", "url": "https://github.com/geniusupgrader/Spandoc", "platforms": ["*"], "sublime_text": ">=3000", "description": "Sublime Text plugin that uses Pandoc to convert text in nearly every possible format into each other and with Spandoc you can use it inside Sublime Text!", "dependencies": []}
```

from my terminal

```bash
╭─ ogi@xps_linux
╰─ which pandoc
/usr/bin/pandoc
```

added the following to `/Packages/User/Spandoc.sublime-settings`

```json
{
    "pandoc_path": "/usr/bin/pandoc"
}
```


With test.md open, running Spandoc: Config up a `spandoc.json` file with the contents:


```json
{
    "pandoc_path": "/usr/bin/pandoc"
}
```

The file I am running `test.md`

```markdown
# Test

this is a test markdown conversion file (test.md)

$$
a^2 + b^2 = c^2
$$
```

Running Spandoc: Palette generates no output, but opening up the console shows the following error:

```
Spandoc: current file path: /home/ogi/test.md
Spandoc: Is the settings file "spandoc.json" in the current folder path?
Spandoc: Yes!
Spandoc: settings_file: {'pandoc_path': '/usr/bin/pandoc'}
Traceback (most recent call last):
  File "/opt/sublime_text/sublime_plugin.py", line 797, in run_
    return self.run()
  File "Spandoc in /home/ogi/.config/sublime-text-3/Installed Packages/Spandoc.sublime-package", line 28, in run
  File "Spandoc in /home/ogi/.config/sublime-text-3/Installed Packages/Spandoc.sublime-package", line 39, in get_transformation_list
TypeError: 'NoneType' object is not subscriptable
```

Running Build With: Spandoc results in the following in the console:

```
__init__() got an unexpected keyword argument 'pandoc_path'
[cmd: None]
[dir: /home/ogi]
[path: /usr/local/sbin:/usr/local/bin:/usr/bin:/opt/cuda/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl]
[Finished]
```

If you don't have a linux system handy, I would be happy to try and debug this further.

**Comment by geniusupgrader** [comment]
I appreciate your help.
Ok, you are using the `spandoc.json` inside the same folder as your `test.md` and
I have already seen this failure at my system, it probably means that your `spandoc.json` is corrupt and not valid json. I suspect some coma is missing, or something like that.  Try to run it through a json validotor, favorably this one: https://www.freeformatter.com/json-validator.html
And make sure that it is at least valid json in JavaScript (there are comments allowed, but the commas must be correct)

**Comment by geniusupgrader** [comment]
I've read your text again and noticed that you appended your `spandoc.json`. Please use the `Spandoc config` first, it will copy the correct (valid) json to `spandoc.json` and then change it to your liking.

**Comment by geniusupgrader** [comment]
Wait a moment, I see some typing error again in the source, I will correct them and try it on my own. And then it should work the way I described in my previous post, first execute `Spandoc config` command

**Comment by geniusupgrader** [comment]
ok, I have tried both approaches installing from github to the projects folder and installing from package control. the `Spandoc config` command does not work from package control installation folder "Installed Packages"

**Comment by j9ac9k** [comment]
Sorry, in case of any confusion; I did not manually edit spandoc.json (I just posted the output of the file after I selected Spandoc: Config, but I did manually edit Spandoc.sublime-settings.

How weird that the `Spandoc config` command doesn't work from the package control installation...

If you don't mind me asking, what is `spandoc.json` supposed to have that `Spandoc.sublime-settings` does not cover?

**Comment by j9ac9k** [comment]
Just made a comment on your last commit; I think I see a problem w/ the paths you're referening Spandoc.sublime-settings.

In SpandocCreateConfig.py you're looking for Spandoc.sublime-settings in a Spandoc folder, which on my system anyway, is not present (`Spandoc.sublime-settings` is present in `Packages/User/`)

**Comment by geniusupgrader** [comment]
`spandoc.json` is only for folder settings, otherwise the `Spandoc.sublime-settings` will be used and there can be a `Spandoc.sublime-settings` in the user folder. Maybe there is a naming conflict, because they are called exactly the same. I have renamed them.

**Comment by j9ac9k** [comment]
got 3.0.7; still having the same issue.

In case it helps:

```
╭─ ogi@xps_linux
╰─ find ~/.config/sublime-text-3 -name "Spando*"
/home/ogi/.config/sublime-text-3/Installed Packages/Spandoc.sublime-package
/home/ogi/.config/sublime-text-3/Packages/User/Spandoc.sublime-settings
/home/ogi/.config/sublime-text-3/Packages/User/Spandoc.sublime-build
╭─ ogi@xps_linux
╰─ find ~/.config/sublime-text-3 -name "spando*" 
╭─ ogi@xps_linux
╰─
```

When doing build with spandoc on my test.md file 

```
reloading plugin Spandoc.Spandoc
reloading plugin Spandoc.SpandocCreateConfig
reloading settings Packages/User/Package Control.sublime-settings
reloading settings Packages/User/Preferences.sublime-settings
reloading settings Packages/User/Preferences.sublime-settings
Spandoc: current file path: /home/ogi/test.md
Spandoc: Is the settings file "spandoc.json" in the current folder path?
Spandoc: Yes!
Spandoc: settings_file: {'pandoc_path': '/usr/bin/pandoc'}
Traceback (most recent call last):
  File "/opt/sublime_text/sublime_plugin.py", line 797, in run_
    return self.run()
  File "Spandoc in /home/ogi/.config/sublime-text-3/Installed Packages/Spandoc.sublime-package", line 28, in run
  File "Spandoc in /home/ogi/.config/sublime-text-3/Installed Packages/Spandoc.sublime-package", line 39, in get_transformation_list
TypeError: 'NoneType' object is not subscriptable
loading dictionary Packages/Language - English/en_US.dic
{"apply_css_live": null, "apply_images_live": null, "apply_js_live": null, "path": "test.md", "command": "reload"}
```

**Comment by geniusupgrader** [comment]
`SpandocCreateConfig.py`, Line 26 changed from
s = sublime.load_resource("Packages\Spandoc\Spandoc.sublime-settings")
to:
s = sublime.load_resource("Packages/Spandoc/Spandoc.sublime-settings")

And I had some difficulties with Package Control because of downgrading the version number (its not possible :)). So, the (hopefully) working version should be 3.1.0.

**Comment by j9ac9k** [comment]
Ahh; yeah... I checked to see if the embedded python in sublime text had the pathlib which really makes these errors a non-issue; and sure enough, it does not!

My linux system is down for unrelated reasons, I'll try and test this out as soon as I can.
